---
title: "Importing Data"
output: html_document
---

# Libraries

```{r, libraries}
library(readr)
library(tidyverse)     # for data cleaning and plotting
library(lubridate)     # for date manipulation
library(openintro)     # for the abbr2state() function
library(maps)          # for map data
library(ggmap)         # for mapping points on maps
library(gplots)        # for col2hex() function
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable mapping
library(ggthemes)      # for more themes (including theme_map())
library(plotly)        # for the ggplotly() - basic interactivity
library(gganimate)     # for adding animation layers to ggplots
library(gifski)        # for creating the gif (don't need to load this library every time,but need it installed)
library(transformr)    # for "tweening" (gganimate)
library(shiny)         # for creating interactive apps
library(patchwork)     # for nicely combining ggplot2 graphs  
library(gt)            # for creating nice tables
library(rvest)         # for scraping data
library(robotstxt)     # for checking if you can scrape data
library(janitor)
library(reshape2)
library(hablar) # Might need to install the hablar package, this gives you the retype function.
```

# Code for importing the Stephen Curry, Warriors, and League Average Data

```{r}
curry_web <- read_html("https://www.basketball-reference.com/players/c/curryst01.html")
warriors_web <- read_html("https://www.basketball-reference.com/teams/GSW/stats_per_game_totals.html")
league_web <- read_html("https://www.basketball-reference.com/leagues/NBA_stats_per_game.html")
lebron_web <- read_html("https://www.basketball-reference.com/players/j/jamesle01.html")
jordan_web <- read_html("https://www.basketball-reference.com/players/j/jordami01.html")

curry_career_regular_season_per_game <- curry_web %>% 
  html_element("#per_game") %>% 
  html_table() %>% 
  clean_names() %>% 
  mutate(season_start_year = as.integer(substr(season, 1, 4))) %>%
  mutate(player = "Stephen Curry")

curry_career_playoffs_per_game <- curry_web %>% 
  html_element("#div_playoffs_per_game") %>% 
  html_table() %>% 
  clean_names() %>% 
  mutate(season_start_year = as.integer(substr(season, 1, 4))) %>% 
  mutate(player = "Stephen Curry")

warriors_per_game_stats <- warriors_web %>% 
  html_element("#stats") %>% 
  html_table() %>% 
  clean_names() %>% 
  discard(~all(is.na(.) | . =="")) %>% #for if there are blank columns
  filter(season != "Season") %>% #discard the rows where it just has the names
  retype() %>% 
  mutate(season_start_year = as.integer(substr(season, 1, 4)))

league_avg_per_game_stats <- league_web %>% 
  html_element("#stats") %>% 
  html_table %>% 
  row_to_names(row_number = 1) %>%  
  clean_names() %>% 
  discard(~all(is.na(.) | . =="")) %>% #for if there are blank columns
  filter(season != "Season" & season != "") %>%  #discard the rows where it just has the names
  retype() %>% 
  mutate(season_start_year = as.integer(substr(season, 1, 4)))

lebron_career_regular_season_per_game <- lebron_web %>% 
  html_element("#per_game") %>% 
  html_table() %>% 
  clean_names() %>% 
  filter(season != "") %>% 
  mutate(season_start_year = as.integer(substr(season, 1, 4))) %>%
  mutate(player = "Lebron James") %>% 
  retype()

lebron_career_playoffs_per_game <- lebron_web %>% 
  html_element("#div_playoffs_per_game") %>% 
  html_table() %>% 
  clean_names() %>% 
  filter(season != "") %>% 
  mutate(season_start_year = as.integer(substr(season, 1, 4))) %>% 
  mutate(player = "Lebron James") %>% 
  retype()

jordan_career_regular_season_per_game <- jordan_web %>% 
  html_element("#per_game") %>% 
  html_table() %>% 
  clean_names() %>%
  filter(lg == "NBA") %>% 
  mutate(season_start_year = as.integer(substr(season, 1, 4))) %>%
  mutate(player = "Michael Jordan") %>% 
  retype()

jordan_career_playoffs_per_game <- jordan_web %>% 
  html_element("#div_playoffs_per_game") %>% 
  html_table() %>% 
  clean_names() %>% 
  filter(season != "") %>% 
  mutate(season_start_year = as.integer(substr(season, 1, 4))) %>% 
  mutate(player = "Michael Jordan") %>% 
  retype()

three_player_career_regular_season_per_game <- rbind(curry_career_regular_season_per_game,
                                                     lebron_career_regular_season_per_game,
                                                     jordan_career_regular_season_per_game)

three_player_career_playoffs_per_game <- rbind(curry_career_playoffs_per_game,
                                               lebron_career_playoffs_per_game,
                                               jordan_career_playoffs_per_game)
```

